name: Electron Builder Action
author: Dmitry Kostenevich
description: GitHub Action for building and releasing Electron apps

inputs:
  github_token:
    description: GitHub authentication token
    required: true
    default: ""
  do_key_id:
    description: Digital Ocean Key Id
    required: true
    default: ""
  do_secret_key:
    description: Digital Ocean secret key
    required: true
    default: ""
  provider:
    description: Cloud provider
    required: true
    default: "github"
  mac_certs:
    description: Base64-encoded code signing certificate for macOS
    required: false
  mac_certs_password:
    description: Password for decrypting `mac_certs`
    required: false
      mac_certs:
  description: Base64-encoded code signing certificate for macOS
    required: false
  apple_id:
    description: Apple Id for notarization process
    required: false
  apple_id_pass:
    description: Apple Id Pass for notarization process
    required: false
  windows_certs:
    description: Base64-encoded code signing certificate for Windows
    required: false
  windows_certs_password:
    description: Password for decrypting `windows_certs`
    required: false
  package_root:
    description: Directory where NPM/Yarn commands should be run
    required: false
    default: "."

runs:
  using: node12
  main: index.js

branding:
  icon: upload-cloud
  color: red
